### ISSUE TITLE
Adonis Client -> Core -> Service -> UIS attempts to resume a non-suspended coroutine

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#49] opened 2018-06-21 18:30 UTC
![image](https://user-images.githubusercontent.com/24907394/41738273-34eb43b8-7557-11e8-85e1-e18b9537f8dc.png)

Probably from a key bind but I'm not sure.
Player commands are disabled too so derp.

**Comment by Sceleratis** [comment] 2018-10-04 00:45
Not sure what the cause it. Haven't seen it happening in testing so closing for now.

**Closed by Sceleratis** 2018-10-04 00:45 UTC
