### ISSUE TITLE
Anti-Cheat Kicking Players

### ISSUE THREAD

**Issue by BrianN4523** [Sceleratis/Adonis#861] opened 2022-07-18 03:47 UTC
What are the steps that lead to the bug occurring? / How frequently does the bug occur?
- Not sure what the steps are for this bug to occur, and it occurs frequently with some users, but not all.

What is the impact of this bug?
- Some players aren't able to play the game.

[Image for context](https://imgur.com/a/0FqaNu0)

**Comment by GGshor** [comment] 2022-07-18 05:22
Found the detection [here](https://github.com/Sceleratis/Adonis/blob/6c3df2b47aa46a42bcf8ea915aa6d1ff17bcd91c/MainModule/Client/Core/Anti.lua#L515).
You should look at your dev console as that might contain the reason why it detects "failed to parse json".

**Comment by Expertcoderz** [comment] 2022-07-18 07:14
Thanks for your report; we'll look into this issue and update you once a fix has been published.

**Comment by Expertcoderz** [comment] 2022-07-20 12:55
It seems that this issue is caused by a script in your own game. Check if your game contains any possibly malicious scripts or scripts that may cause the message "failed to parse json" to be outputted on a player's client.

One way that might help is to press Ctrl+Shift+F and search for "failed to parse json".

**Closed** 2022-07-20 12:57 UTC
Labels: bug, anti-exploit
