### ISSUE TITLE
ServerInfo doesn't work and produces an error.

### ISSUE THREAD

**Issue by TheMysticc** [Sceleratis/Adonis#370] opened 2021-06-18 11:09 UTC
![Screenshot_11](https://user-images.githubusercontent.com/78848081/122552216-5d4ed600-d079-11eb-9d5c-4612f15d4a97.png)

Reproduction Steps:
- Run :serverinfo in the command bar or chat then check your F9 console (Client)

**Comment by LolloDev5123** [comment] 2021-06-18 12:41
Yeah um, that's caused by ExpertCoder who tried to turn ServerDetails into a GUI with Tabs.
Still don't know why no one is noticing this

**Comment by Expertcoderz** [comment] 2021-06-18 14:45
Hmm...`"GUI ServerDetails not found`? That's strange, I'll look into it sometime soon.

**Comment by Expertcoderz** [comment] 2021-07-03 06:30
This has been fixed long ago, can someone close the issue?

**Comment by DavidBaszuckiA** [comment] 2021-07-05 00:44
That action would require upgrading to Premium Adonis.

**Comment by GalacticInspired** [comment] 2021-07-05 12:01
> That action would require upgrading to Premium Adonis.

From our research, it has been found that **Premium Adonis** contains malicious contents and the game’s creator will be notified to remove it from their game. https://github.com/Sceleratis/Adonis/commit/24e48a5dbd5f5ec830b70a743928d3a3b6d929c8

Don’t worry, you won’t stay long on this github.

**Closed** 2021-07-07 15:36 UTC
